@extends('layouts.app')
@section('title', $lead->name)
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h4 class="fw-bold mb-0">{{ $lead->name }}</h4><small class="text-muted">{{ $lead->lead_id }} | {{ $lead->company_name }}</small></div><div class="d-flex gap-2"><a href="{{ route('admin.followups.create', ['lead_id'=>$lead->id]) }}" class="btn btn-outline-primary btn-sm"><i class="bi bi-telephone-plus me-1"></i>Follow-Up</a><a href="{{ route('admin.quotations.create', ['lead_id'=>$lead->id]) }}" class="btn btn-outline-success btn-sm"><i class="bi bi-file-earmark-plus me-1"></i>Quotation</a><a href="{{ route('admin.leads.edit', $lead) }}" class="btn btn-primary btn-sm"><i class="bi bi-pencil me-1"></i>Edit</a></div></div>
<div class="row g-4"><div class="col-lg-8"><div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="row g-3"><div class="col-sm-6"><small class="text-muted">Email</small><div>{{ $lead->email ?? '-' }}</div></div><div class="col-sm-6"><small class="text-muted">Phone</small><div>{{ $lead->phone ?? '-' }}</div></div><div class="col-sm-6"><small class="text-muted">WhatsApp</small><div>{{ $lead->whatsapp_number ?? '-' }}</div></div><div class="col-sm-6"><small class="text-muted">Company</small><div>{{ $lead->company_name ?? '-' }}</div></div><div class="col-sm-6"><small class="text-muted">Budget</small><div>{{ $lead->budget ? format_currency($lead->budget) : '-' }}</div></div><div class="col-sm-6"><small class="text-muted">Deal Value</small><div>{{ $lead->deal_value ? format_currency($lead->deal_value) : '-' }}</div></div><div class="col-12"><small class="text-muted">Requirement</small><div>{{ $lead->requirement ?? '-' }}</div></div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-transparent"><h6 class="mb-0">Activity Timeline</h6></div><div class="card-body">@forelse($lead->activities as $a)<div class="d-flex mb-3"><div class="me-3"><div class="bg-primary bg-opacity-10 rounded-circle d-flex align-items-center justify-content-center" style="width:32px;height:32px"><i class="bi bi-clock text-primary small"></i></div></div><div><div class="fw-semibold">{{ $a->title }}</div><small class="text-muted">{{ $a->description }}</small><div class="text-muted small">{{ $a->user->name ?? 'System' }} - {{ $a->created_at->diffForHumans() }}</div></div></div>@empty<p class="text-muted text-center">No activities yet.</p>@endforelse</div></div></div>
<div class="col-lg-4"><div class="card border-0 shadow-sm mb-4"><div class="card-body"><div class="mb-3"><small class="text-muted">Status</small><div><span class="badge bg-{{ $lead->status_badge }} fs-6">{{ ucfirst(str_replace('_',' ',$lead->status)) }}</span></div></div><div class="mb-3"><small class="text-muted">Priority</small><div><span class="badge bg-{{ $lead->priority_badge }}">{{ ucfirst($lead->priority) }}</span></div></div><div class="mb-3"><small class="text-muted">Source</small><div>{{ config('crm.lead_sources.'.$lead->source, $lead->source) }}</div></div><div class="mb-3"><small class="text-muted">Assigned To</small><div>{{ $lead->assignedTo->name ?? 'Unassigned' }}</div></div><div class="mb-3"><small class="text-muted">Score</small><div><div class="progress" style="height:8px"><div class="progress-bar" style="width:{{ $lead->score }}%"></div></div><small>{{ $lead->score }}/100</small></div></div><div><small class="text-muted">Created</small><div>{{ $lead->created_at->format('d M Y, h:i A') }}</div></div></div></div>
<div class="card border-0 shadow-sm"><div class="card-header bg-transparent d-flex justify-content-between"><h6 class="mb-0">Follow-Ups</h6><a href="{{ route('admin.followups.create', ['lead_id'=>$lead->id]) }}" class="btn btn-sm btn-outline-primary">Add</a></div><div class="card-body p-0"><div class="list-group list-group-flush">@forelse($lead->followUps->take(5) as $f)<div class="list-group-item"><div class="d-flex justify-content-between"><strong class="small">{{ $f->title }}</strong><span class="badge bg-{{ $f->status_badge }}">{{ ucfirst($f->status) }}</span></div><small class="text-muted">{{ $f->scheduled_at->format('d M Y, h:i A') }}</small></div>@empty<div class="list-group-item text-center text-muted small">No follow-ups</div>@endforelse</div></div></div></div></div>
@endsection
