<nav class="navbar navbar-expand-lg bg-body-tertiary border-bottom px-4 py-2">
    <div class="container-fluid">
        <button class="btn btn-sm btn-outline-secondary me-3" id="sidebarToggle"><i class="bi bi-list"></i></button>
        <form class="d-none d-md-flex me-auto" action="{{ route('admin.leads.index') }}" method="GET">
            <div class="input-group" style="width:300px"><input type="text" name="search" class="form-control form-control-sm" placeholder="Search leads, clients..."><button class="btn btn-outline-secondary btn-sm" type="submit"><i class="bi bi-search"></i></button></div>
        </form>
        <div class="d-flex align-items-center gap-3">
            <div class="dropdown"><button class="btn btn-primary btn-sm dropdown-toggle" data-bs-toggle="dropdown"><i class="bi bi-plus-lg"></i> New</button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{ route('admin.leads.create') }}"><i class="bi bi-person-plus me-2"></i>New Lead</a></li><li><a class="dropdown-item" href="{{ route('admin.followups.create') }}"><i class="bi bi-telephone-plus me-2"></i>New Follow-Up</a></li><li><a class="dropdown-item" href="{{ route('admin.quotations.create') }}"><i class="bi bi-file-earmark-plus me-2"></i>New Quotation</a></li><li><a class="dropdown-item" href="{{ route('admin.tasks.create') }}"><i class="bi bi-plus-square me-2"></i>New Task</a></li></ul></div>
            <button class="btn btn-sm btn-outline-secondary" id="themeToggle" title="Toggle Dark Mode"><i class="bi bi-moon-stars"></i></button>
            <div class="dropdown"><button class="btn btn-sm btn-outline-secondary position-relative" data-bs-toggle="dropdown"><i class="bi bi-bell"></i>@if(auth()->user()->unreadNotifications->count() > 0)<span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">{{ auth()->user()->unreadNotifications->count() }}</span>@endif</button><div class="dropdown-menu dropdown-menu-end" style="width:320px"><h6 class="dropdown-header">Notifications</h6>@forelse(auth()->user()->unreadNotifications->take(5) as $n)<a class="dropdown-item small" href="#">{{ $n->data['title'] ?? 'Notification' }}<br><small class="text-muted">{{ $n->created_at->diffForHumans() }}</small></a>@empty<div class="dropdown-item text-center text-muted small">No new notifications</div>@endforelse<div class="dropdown-divider"></div><a class="dropdown-item text-center small" href="{{ route('admin.notifications.index') }}">View All</a></div></div>
            <div class="dropdown"><button class="btn btn-sm d-flex align-items-center gap-2" data-bs-toggle="dropdown"><img src="{{ auth()->user()->avatar_url }}" class="rounded-circle" width="32" height="32"><span class="d-none d-md-inline">{{ auth()->user()->name }}</span><i class="bi bi-chevron-down small"></i></button><ul class="dropdown-menu dropdown-menu-end"><li><a class="dropdown-item" href="{{ route('admin.profile.edit') }}"><i class="bi bi-person me-2"></i>Profile</a></li><li><a class="dropdown-item" href="{{ route('admin.settings.index') }}"><i class="bi bi-gear me-2"></i>Settings</a></li><li><hr class="dropdown-divider"></li><li><form action="{{ route('logout') }}" method="POST">@csrf<button type="submit" class="dropdown-item text-danger"><i class="bi bi-box-arrow-right me-2"></i>Logout</button></form></li></ul></div>
        </div>
    </div>
</nav>
