@extends('layouts.app')
@section('title', 'Settings')
@section('content')
<h4 class="fw-bold mb-4">Settings</h4>
<div class="row g-4"><div class="col-md-3"><div class="list-group"><a href="#general" class="list-group-item list-group-item-action active" data-bs-toggle="list">General</a><a href="#email" class="list-group-item list-group-item-action" data-bs-toggle="list">Email/SMTP</a><a href="#google" class="list-group-item list-group-item-action" data-bs-toggle="list">Google API</a><a href="#whatsapp" class="list-group-item list-group-item-action" data-bs-toggle="list">WhatsApp</a><a href="#branding" class="list-group-item list-group-item-action" data-bs-toggle="list">Branding</a><a href="{{ route('admin.settings.white-label') }}" class="list-group-item list-group-item-action">White Label</a></div></div>
<div class="col-md-9"><div class="tab-content"><div class="tab-pane fade show active" id="general"><div class="card border-0 shadow-sm"><div class="card-header bg-transparent"><h6 class="mb-0">General Settings</h6></div><div class="card-body"><form method="POST" action="{{ route('admin.settings.general') }}">@csrf<div class="row g-3"><div class="col-md-6"><label class="form-label">Company Name</label><input type="text" name="company_name" class="form-control" value="{{ setting('company_name') }}"></div><div class="col-md-6"><label class="form-label">Email</label><input type="email" name="company_email" class="form-control" value="{{ setting('company_email') }}"></div><div class="col-md-6"><label class="form-label">Phone</label><input type="text" name="company_phone" class="form-control" value="{{ setting('company_phone') }}"></div><div class="col-md-3"><label class="form-label">Currency</label><select name="currency" class="form-select"><option value="INR" {{ setting('currency')=='INR'?'selected':'' }}>INR</option><option value="USD" {{ setting('currency')=='USD'?'selected':'' }}>USD</option><option value="EUR" {{ setting('currency')=='EUR'?'selected':'' }}>EUR</option></select></div><div class="col-md-3"><label class="form-label">Timezone</label><input type="text" name="timezone" class="form-control" value="{{ setting('timezone','Asia/Kolkata') }}"></div></div><button type="submit" class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="tab-pane fade" id="email"><div class="card border-0 shadow-sm"><div class="card-header bg-transparent"><h6 class="mb-0">SMTP Settings</h6></div><div class="card-body"><form method="POST" action="{{ route('admin.settings.email') }}">@csrf<div class="row g-3"><div class="col-md-8"><label class="form-label">SMTP Host</label><input type="text" name="mail_host" class="form-control" value="{{ setting('mail_host','smtp.gmail.com') }}"></div><div class="col-md-4"><label class="form-label">Port</label><input type="number" name="mail_port" class="form-control" value="{{ setting('mail_port','587') }}"></div><div class="col-md-6"><label class="form-label">Username</label><input type="text" name="mail_username" class="form-control" value="{{ setting('mail_username') }}"></div><div class="col-md-6"><label class="form-label">Password</label><input type="password" name="mail_password" class="form-control"></div><div class="col-md-6"><label class="form-label">From Address</label><input type="email" name="mail_from_address" class="form-control" value="{{ setting('mail_from_address') }}"></div><div class="col-md-6"><label class="form-label">From Name</label><input type="text" name="mail_from_name" class="form-control" value="{{ setting('mail_from_name') }}"></div></div><button type="submit" class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="tab-pane fade" id="google"><div class="card border-0 shadow-sm"><div class="card-body"><form method="POST" action="{{ route('admin.settings.google') }}">@csrf<div class="mb-3"><label class="form-label">Client ID</label><input type="text" name="google_client_id" class="form-control" value="{{ setting('google_client_id') }}"></div><div class="mb-3"><label class="form-label">Client Secret</label><input type="password" name="google_client_secret" class="form-control"></div><div class="alert alert-info small">Redirect URI: <code>{{ url('/auth/google/callback') }}</code></div><button type="submit" class="btn btn-primary">Save</button></form></div></div></div>
<div class="tab-pane fade" id="whatsapp"><div class="card border-0 shadow-sm"><div class="card-body"><form method="POST" action="{{ route('admin.settings.whatsapp') }}">@csrf<div class="mb-3"><label class="form-label">Phone Number ID</label><input type="text" name="whatsapp_phone_number_id" class="form-control" value="{{ setting('whatsapp_phone_number_id') }}"></div><div class="mb-3"><label class="form-label">Access Token</label><input type="password" name="whatsapp_access_token" class="form-control"></div><div class="alert alert-info small">Webhook: <code>{{ url('/api/v1/whatsapp/webhook') }}</code></div><button type="submit" class="btn btn-primary">Save</button></form></div></div></div>
<div class="tab-pane fade" id="branding"><div class="card border-0 shadow-sm"><div class="card-body"><form method="POST" action="{{ route('admin.settings.branding') }}" enctype="multipart/form-data">@csrf<div class="mb-3"><label class="form-label">Logo</label><input type="file" name="logo" class="form-control" accept="image/*"></div><div class="mb-3"><label class="form-label">Favicon</label><input type="file" name="favicon" class="form-control" accept="image/*"></div><button type="submit" class="btn btn-primary">Upload</button></form></div></div></div></div></div></div>
@endsection
